//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TK1ClientBizzModel", "PropertyAdPropertyAdDetail", "PropertyAd", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TK1.Bizz.Client.Data.PropertyAd), "PropertyAdDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TK1.Bizz.Client.Data.PropertyAdDetail), true)]
[assembly: EdmRelationshipAttribute("TK1ClientBizzModel", "PropertyAdPropertyAdPic", "PropertyAd", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TK1.Bizz.Client.Data.PropertyAd), "PropertyAdPic", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TK1.Bizz.Client.Data.PropertyAdPic), true)]

#endregion

namespace TK1.Bizz.Client.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TK1ClientBizzEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TK1ClientBizzEntities object using the connection string found in the 'TK1ClientBizzEntities' section of the application configuration file.
        /// </summary>
        public TK1ClientBizzEntities() : base("name=TK1ClientBizzEntities", "TK1ClientBizzEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TK1ClientBizzEntities object.
        /// </summary>
        public TK1ClientBizzEntities(string connectionString) : base(connectionString, "TK1ClientBizzEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TK1ClientBizzEntities object.
        /// </summary>
        public TK1ClientBizzEntities(EntityConnection connection) : base(connection, "TK1ClientBizzEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PropertyAd> PropertyAd
        {
            get
            {
                if ((_PropertyAd == null))
                {
                    _PropertyAd = base.CreateObjectSet<PropertyAd>("PropertyAd");
                }
                return _PropertyAd;
            }
        }
        private ObjectSet<PropertyAd> _PropertyAd;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PropertyAdDetail> PropertyAdDetail
        {
            get
            {
                if ((_PropertyAdDetail == null))
                {
                    _PropertyAdDetail = base.CreateObjectSet<PropertyAdDetail>("PropertyAdDetail");
                }
                return _PropertyAdDetail;
            }
        }
        private ObjectSet<PropertyAdDetail> _PropertyAdDetail;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PropertyAdPic> PropertyAdPic
        {
            get
            {
                if ((_PropertyAdPic == null))
                {
                    _PropertyAdPic = base.CreateObjectSet<PropertyAdPic>("PropertyAdPic");
                }
                return _PropertyAdPic;
            }
        }
        private ObjectSet<PropertyAdPic> _PropertyAdPic;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PropertyReleaseAd> PropertyReleaseAd
        {
            get
            {
                if ((_PropertyReleaseAd == null))
                {
                    _PropertyReleaseAd = base.CreateObjectSet<PropertyReleaseAd>("PropertyReleaseAd");
                }
                return _PropertyReleaseAd;
            }
        }
        private ObjectSet<PropertyReleaseAd> _PropertyReleaseAd;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PropertyAd EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPropertyAd(PropertyAd propertyAd)
        {
            base.AddObject("PropertyAd", propertyAd);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PropertyAdDetail EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPropertyAdDetail(PropertyAdDetail propertyAdDetail)
        {
            base.AddObject("PropertyAdDetail", propertyAdDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PropertyAdPic EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPropertyAdPic(PropertyAdPic propertyAdPic)
        {
            base.AddObject("PropertyAdPic", propertyAdPic);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PropertyReleaseAd EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPropertyReleaseAd(PropertyReleaseAd propertyReleaseAd)
        {
            base.AddObject("PropertyReleaseAd", propertyReleaseAd);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TK1ClientBizzModel", Name="PropertyAd")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PropertyAd : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PropertyAd object.
        /// </summary>
        /// <param name="propertyAdID">Initial value of the PropertyAdID property.</param>
        /// <param name="propertyAdTypeID">Initial value of the PropertyAdTypeID property.</param>
        /// <param name="customerCode">Initial value of the CustomerCode property.</param>
        /// <param name="propertyAdStatusID">Initial value of the PropertyAdStatusID property.</param>
        /// <param name="categoryName">Initial value of the CategoryName property.</param>
        /// <param name="propertyTypeName">Initial value of the PropertyTypeName property.</param>
        /// <param name="cityName">Initial value of the CityName property.</param>
        /// <param name="districtName">Initial value of the DistrictName property.</param>
        /// <param name="totalArea">Initial value of the TotalArea property.</param>
        /// <param name="totalRooms">Initial value of the TotalRooms property.</param>
        /// <param name="internalArea">Initial value of the InternalArea property.</param>
        /// <param name="externalArea">Initial value of the ExternalArea property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        /// <param name="featured">Initial value of the Featured property.</param>
        /// <param name="visible">Initial value of the Visible property.</param>
        public static PropertyAd CreatePropertyAd(global::System.Int32 propertyAdID, global::System.String propertyAdTypeID, global::System.String customerCode, global::System.String propertyAdStatusID, global::System.String categoryName, global::System.String propertyTypeName, global::System.String cityName, global::System.String districtName, global::System.Single totalArea, global::System.Int32 totalRooms, global::System.Single internalArea, global::System.Single externalArea, global::System.Single value, global::System.Boolean featured, global::System.Boolean visible)
        {
            PropertyAd propertyAd = new PropertyAd();
            propertyAd.PropertyAdID = propertyAdID;
            propertyAd.PropertyAdTypeID = propertyAdTypeID;
            propertyAd.CustomerCode = customerCode;
            propertyAd.PropertyAdStatusID = propertyAdStatusID;
            propertyAd.CategoryName = categoryName;
            propertyAd.PropertyTypeName = propertyTypeName;
            propertyAd.CityName = cityName;
            propertyAd.DistrictName = districtName;
            propertyAd.TotalArea = totalArea;
            propertyAd.TotalRooms = totalRooms;
            propertyAd.InternalArea = internalArea;
            propertyAd.ExternalArea = externalArea;
            propertyAd.Value = value;
            propertyAd.Featured = featured;
            propertyAd.Visible = visible;
            return propertyAd;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PropertyAdID
        {
            get
            {
                return _PropertyAdID;
            }
            set
            {
                if (_PropertyAdID != value)
                {
                    OnPropertyAdIDChanging(value);
                    ReportPropertyChanging("PropertyAdID");
                    _PropertyAdID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PropertyAdID");
                    OnPropertyAdIDChanged();
                }
            }
        }
        private global::System.Int32 _PropertyAdID;
        partial void OnPropertyAdIDChanging(global::System.Int32 value);
        partial void OnPropertyAdIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PropertyAdTypeID
        {
            get
            {
                return _PropertyAdTypeID;
            }
            set
            {
                if (_PropertyAdTypeID != value)
                {
                    OnPropertyAdTypeIDChanging(value);
                    ReportPropertyChanging("PropertyAdTypeID");
                    _PropertyAdTypeID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PropertyAdTypeID");
                    OnPropertyAdTypeIDChanged();
                }
            }
        }
        private global::System.String _PropertyAdTypeID;
        partial void OnPropertyAdTypeIDChanging(global::System.String value);
        partial void OnPropertyAdTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerCode
        {
            get
            {
                return _CustomerCode;
            }
            set
            {
                if (_CustomerCode != value)
                {
                    OnCustomerCodeChanging(value);
                    ReportPropertyChanging("CustomerCode");
                    _CustomerCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CustomerCode");
                    OnCustomerCodeChanged();
                }
            }
        }
        private global::System.String _CustomerCode;
        partial void OnCustomerCodeChanging(global::System.String value);
        partial void OnCustomerCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PropertyAdStatusID
        {
            get
            {
                return _PropertyAdStatusID;
            }
            set
            {
                OnPropertyAdStatusIDChanging(value);
                ReportPropertyChanging("PropertyAdStatusID");
                _PropertyAdStatusID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PropertyAdStatusID");
                OnPropertyAdStatusIDChanged();
            }
        }
        private global::System.String _PropertyAdStatusID;
        partial void OnPropertyAdStatusIDChanging(global::System.String value);
        partial void OnPropertyAdStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PropertyTypeName
        {
            get
            {
                return _PropertyTypeName;
            }
            set
            {
                OnPropertyTypeNameChanging(value);
                ReportPropertyChanging("PropertyTypeName");
                _PropertyTypeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PropertyTypeName");
                OnPropertyTypeNameChanged();
            }
        }
        private global::System.String _PropertyTypeName;
        partial void OnPropertyTypeNameChanging(global::System.String value);
        partial void OnPropertyTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CityName
        {
            get
            {
                return _CityName;
            }
            set
            {
                OnCityNameChanging(value);
                ReportPropertyChanging("CityName");
                _CityName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CityName");
                OnCityNameChanged();
            }
        }
        private global::System.String _CityName;
        partial void OnCityNameChanging(global::System.String value);
        partial void OnCityNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DistrictName
        {
            get
            {
                return _DistrictName;
            }
            set
            {
                OnDistrictNameChanging(value);
                ReportPropertyChanging("DistrictName");
                _DistrictName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DistrictName");
                OnDistrictNameChanged();
            }
        }
        private global::System.String _DistrictName;
        partial void OnDistrictNameChanging(global::System.String value);
        partial void OnDistrictNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single TotalArea
        {
            get
            {
                return _TotalArea;
            }
            set
            {
                OnTotalAreaChanging(value);
                ReportPropertyChanging("TotalArea");
                _TotalArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalArea");
                OnTotalAreaChanged();
            }
        }
        private global::System.Single _TotalArea;
        partial void OnTotalAreaChanging(global::System.Single value);
        partial void OnTotalAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalRooms
        {
            get
            {
                return _TotalRooms;
            }
            set
            {
                OnTotalRoomsChanging(value);
                ReportPropertyChanging("TotalRooms");
                _TotalRooms = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalRooms");
                OnTotalRoomsChanged();
            }
        }
        private global::System.Int32 _TotalRooms;
        partial void OnTotalRoomsChanging(global::System.Int32 value);
        partial void OnTotalRoomsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single InternalArea
        {
            get
            {
                return _InternalArea;
            }
            set
            {
                OnInternalAreaChanging(value);
                ReportPropertyChanging("InternalArea");
                _InternalArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InternalArea");
                OnInternalAreaChanged();
            }
        }
        private global::System.Single _InternalArea;
        partial void OnInternalAreaChanging(global::System.Single value);
        partial void OnInternalAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single ExternalArea
        {
            get
            {
                return _ExternalArea;
            }
            set
            {
                OnExternalAreaChanging(value);
                ReportPropertyChanging("ExternalArea");
                _ExternalArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExternalArea");
                OnExternalAreaChanged();
            }
        }
        private global::System.Single _ExternalArea;
        partial void OnExternalAreaChanging(global::System.Single value);
        partial void OnExternalAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Single _Value;
        partial void OnValueChanging(global::System.Single value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CityTaxes
        {
            get
            {
                return _CityTaxes;
            }
            set
            {
                OnCityTaxesChanging(value);
                ReportPropertyChanging("CityTaxes");
                _CityTaxes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CityTaxes");
                OnCityTaxesChanged();
            }
        }
        private Nullable<global::System.Single> _CityTaxes;
        partial void OnCityTaxesChanging(Nullable<global::System.Single> value);
        partial void OnCityTaxesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CondoTaxes
        {
            get
            {
                return _CondoTaxes;
            }
            set
            {
                OnCondoTaxesChanging(value);
                ReportPropertyChanging("CondoTaxes");
                _CondoTaxes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CondoTaxes");
                OnCondoTaxesChanged();
            }
        }
        private Nullable<global::System.Single> _CondoTaxes;
        partial void OnCondoTaxesChanging(Nullable<global::System.Single> value);
        partial void OnCondoTaxesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShortDescription
        {
            get
            {
                return _ShortDescription;
            }
            set
            {
                OnShortDescriptionChanging(value);
                ReportPropertyChanging("ShortDescription");
                _ShortDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShortDescription");
                OnShortDescriptionChanged();
            }
        }
        private global::System.String _ShortDescription;
        partial void OnShortDescriptionChanging(global::System.String value);
        partial void OnShortDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Featured
        {
            get
            {
                return _Featured;
            }
            set
            {
                OnFeaturedChanging(value);
                ReportPropertyChanging("Featured");
                _Featured = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Featured");
                OnFeaturedChanged();
            }
        }
        private global::System.Boolean _Featured;
        partial void OnFeaturedChanging(global::System.Boolean value);
        partial void OnFeaturedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private global::System.Boolean _Visible;
        partial void OnVisibleChanging(global::System.Boolean value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullDescription
        {
            get
            {
                return _FullDescription;
            }
            set
            {
                OnFullDescriptionChanging(value);
                ReportPropertyChanging("FullDescription");
                _FullDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullDescription");
                OnFullDescriptionChanged();
            }
        }
        private global::System.String _FullDescription;
        partial void OnFullDescriptionChanging(global::System.String value);
        partial void OnFullDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AreaDescription
        {
            get
            {
                return _AreaDescription;
            }
            set
            {
                OnAreaDescriptionChanging(value);
                ReportPropertyChanging("AreaDescription");
                _AreaDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AreaDescription");
                OnAreaDescriptionChanged();
            }
        }
        private global::System.String _AreaDescription;
        partial void OnAreaDescriptionChanging(global::System.String value);
        partial void OnAreaDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CondoDescription
        {
            get
            {
                return _CondoDescription;
            }
            set
            {
                OnCondoDescriptionChanging(value);
                ReportPropertyChanging("CondoDescription");
                _CondoDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CondoDescription");
                OnCondoDescriptionChanged();
            }
        }
        private global::System.String _CondoDescription;
        partial void OnCondoDescriptionChanging(global::System.String value);
        partial void OnCondoDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PicUrl
        {
            get
            {
                return _PicUrl;
            }
            set
            {
                OnPicUrlChanging(value);
                ReportPropertyChanging("PicUrl");
                _PicUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PicUrl");
                OnPicUrlChanged();
            }
        }
        private global::System.String _PicUrl;
        partial void OnPicUrlChanging(global::System.String value);
        partial void OnPicUrlChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TK1ClientBizzModel", "PropertyAdPropertyAdDetail", "PropertyAdDetail")]
        public EntityCollection<PropertyAdDetail> PropertyAdDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PropertyAdDetail>("TK1ClientBizzModel.PropertyAdPropertyAdDetail", "PropertyAdDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PropertyAdDetail>("TK1ClientBizzModel.PropertyAdPropertyAdDetail", "PropertyAdDetail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TK1ClientBizzModel", "PropertyAdPropertyAdPic", "PropertyAdPic")]
        public EntityCollection<PropertyAdPic> PropertyAdPics
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PropertyAdPic>("TK1ClientBizzModel.PropertyAdPropertyAdPic", "PropertyAdPic");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PropertyAdPic>("TK1ClientBizzModel.PropertyAdPropertyAdPic", "PropertyAdPic", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TK1ClientBizzModel", Name="PropertyAdDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PropertyAdDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PropertyAdDetail object.
        /// </summary>
        /// <param name="propertyAdDetailID">Initial value of the PropertyAdDetailID property.</param>
        /// <param name="propertyAdID">Initial value of the PropertyAdID property.</param>
        /// <param name="propertyAdTypeID">Initial value of the PropertyAdTypeID property.</param>
        /// <param name="customerCode">Initial value of the CustomerCode property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static PropertyAdDetail CreatePropertyAdDetail(global::System.Int32 propertyAdDetailID, global::System.Int32 propertyAdID, global::System.String propertyAdTypeID, global::System.String customerCode, global::System.String type)
        {
            PropertyAdDetail propertyAdDetail = new PropertyAdDetail();
            propertyAdDetail.PropertyAdDetailID = propertyAdDetailID;
            propertyAdDetail.PropertyAdID = propertyAdID;
            propertyAdDetail.PropertyAdTypeID = propertyAdTypeID;
            propertyAdDetail.CustomerCode = customerCode;
            propertyAdDetail.Type = type;
            return propertyAdDetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PropertyAdDetailID
        {
            get
            {
                return _PropertyAdDetailID;
            }
            set
            {
                if (_PropertyAdDetailID != value)
                {
                    OnPropertyAdDetailIDChanging(value);
                    ReportPropertyChanging("PropertyAdDetailID");
                    _PropertyAdDetailID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PropertyAdDetailID");
                    OnPropertyAdDetailIDChanged();
                }
            }
        }
        private global::System.Int32 _PropertyAdDetailID;
        partial void OnPropertyAdDetailIDChanging(global::System.Int32 value);
        partial void OnPropertyAdDetailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PropertyAdID
        {
            get
            {
                return _PropertyAdID;
            }
            set
            {
                OnPropertyAdIDChanging(value);
                ReportPropertyChanging("PropertyAdID");
                _PropertyAdID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PropertyAdID");
                OnPropertyAdIDChanged();
            }
        }
        private global::System.Int32 _PropertyAdID;
        partial void OnPropertyAdIDChanging(global::System.Int32 value);
        partial void OnPropertyAdIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PropertyAdTypeID
        {
            get
            {
                return _PropertyAdTypeID;
            }
            set
            {
                OnPropertyAdTypeIDChanging(value);
                ReportPropertyChanging("PropertyAdTypeID");
                _PropertyAdTypeID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PropertyAdTypeID");
                OnPropertyAdTypeIDChanged();
            }
        }
        private global::System.String _PropertyAdTypeID;
        partial void OnPropertyAdTypeIDChanging(global::System.String value);
        partial void OnPropertyAdTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerCode
        {
            get
            {
                return _CustomerCode;
            }
            set
            {
                OnCustomerCodeChanging(value);
                ReportPropertyChanging("CustomerCode");
                _CustomerCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerCode");
                OnCustomerCodeChanged();
            }
        }
        private global::System.String _CustomerCode;
        partial void OnCustomerCodeChanging(global::System.String value);
        partial void OnCustomerCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TK1ClientBizzModel", "PropertyAdPropertyAdDetail", "PropertyAd")]
        public PropertyAd PropertyAd
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PropertyAd>("TK1ClientBizzModel.PropertyAdPropertyAdDetail", "PropertyAd").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PropertyAd>("TK1ClientBizzModel.PropertyAdPropertyAdDetail", "PropertyAd").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PropertyAd> PropertyAdReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PropertyAd>("TK1ClientBizzModel.PropertyAdPropertyAdDetail", "PropertyAd");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PropertyAd>("TK1ClientBizzModel.PropertyAdPropertyAdDetail", "PropertyAd", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TK1ClientBizzModel", Name="PropertyAdPic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PropertyAdPic : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PropertyAdPic object.
        /// </summary>
        /// <param name="propertyAdPicID">Initial value of the PropertyAdPicID property.</param>
        /// <param name="propertyAdID">Initial value of the PropertyAdID property.</param>
        /// <param name="propertyAdTypeID">Initial value of the PropertyAdTypeID property.</param>
        /// <param name="customerCode">Initial value of the CustomerCode property.</param>
        public static PropertyAdPic CreatePropertyAdPic(global::System.Int32 propertyAdPicID, global::System.Int32 propertyAdID, global::System.String propertyAdTypeID, global::System.String customerCode)
        {
            PropertyAdPic propertyAdPic = new PropertyAdPic();
            propertyAdPic.PropertyAdPicID = propertyAdPicID;
            propertyAdPic.PropertyAdID = propertyAdID;
            propertyAdPic.PropertyAdTypeID = propertyAdTypeID;
            propertyAdPic.CustomerCode = customerCode;
            return propertyAdPic;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PropertyAdPicID
        {
            get
            {
                return _PropertyAdPicID;
            }
            set
            {
                if (_PropertyAdPicID != value)
                {
                    OnPropertyAdPicIDChanging(value);
                    ReportPropertyChanging("PropertyAdPicID");
                    _PropertyAdPicID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PropertyAdPicID");
                    OnPropertyAdPicIDChanged();
                }
            }
        }
        private global::System.Int32 _PropertyAdPicID;
        partial void OnPropertyAdPicIDChanging(global::System.Int32 value);
        partial void OnPropertyAdPicIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PropertyAdID
        {
            get
            {
                return _PropertyAdID;
            }
            set
            {
                OnPropertyAdIDChanging(value);
                ReportPropertyChanging("PropertyAdID");
                _PropertyAdID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PropertyAdID");
                OnPropertyAdIDChanged();
            }
        }
        private global::System.Int32 _PropertyAdID;
        partial void OnPropertyAdIDChanging(global::System.Int32 value);
        partial void OnPropertyAdIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PropertyAdTypeID
        {
            get
            {
                return _PropertyAdTypeID;
            }
            set
            {
                OnPropertyAdTypeIDChanging(value);
                ReportPropertyChanging("PropertyAdTypeID");
                _PropertyAdTypeID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PropertyAdTypeID");
                OnPropertyAdTypeIDChanged();
            }
        }
        private global::System.String _PropertyAdTypeID;
        partial void OnPropertyAdTypeIDChanging(global::System.String value);
        partial void OnPropertyAdTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerCode
        {
            get
            {
                return _CustomerCode;
            }
            set
            {
                OnCustomerCodeChanging(value);
                ReportPropertyChanging("CustomerCode");
                _CustomerCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerCode");
                OnCustomerCodeChanged();
            }
        }
        private global::System.String _CustomerCode;
        partial void OnCustomerCodeChanging(global::System.String value);
        partial void OnCustomerCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PictureUrl
        {
            get
            {
                return _PictureUrl;
            }
            set
            {
                OnPictureUrlChanging(value);
                ReportPropertyChanging("PictureUrl");
                _PictureUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PictureUrl");
                OnPictureUrlChanged();
            }
        }
        private global::System.String _PictureUrl;
        partial void OnPictureUrlChanging(global::System.String value);
        partial void OnPictureUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ThumbnailUrl
        {
            get
            {
                return _ThumbnailUrl;
            }
            set
            {
                OnThumbnailUrlChanging(value);
                ReportPropertyChanging("ThumbnailUrl");
                _ThumbnailUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThumbnailUrl");
                OnThumbnailUrlChanged();
            }
        }
        private global::System.String _ThumbnailUrl;
        partial void OnThumbnailUrlChanging(global::System.String value);
        partial void OnThumbnailUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PictureFilePath
        {
            get
            {
                return _PictureFilePath;
            }
            set
            {
                OnPictureFilePathChanging(value);
                ReportPropertyChanging("PictureFilePath");
                _PictureFilePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PictureFilePath");
                OnPictureFilePathChanged();
            }
        }
        private global::System.String _PictureFilePath;
        partial void OnPictureFilePathChanging(global::System.String value);
        partial void OnPictureFilePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ThumbnailFilePath
        {
            get
            {
                return _ThumbnailFilePath;
            }
            set
            {
                OnThumbnailFilePathChanging(value);
                ReportPropertyChanging("ThumbnailFilePath");
                _ThumbnailFilePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThumbnailFilePath");
                OnThumbnailFilePathChanged();
            }
        }
        private global::System.String _ThumbnailFilePath;
        partial void OnThumbnailFilePathChanging(global::System.String value);
        partial void OnThumbnailFilePathChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TK1ClientBizzModel", "PropertyAdPropertyAdPic", "PropertyAd")]
        public PropertyAd PropertyAd
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PropertyAd>("TK1ClientBizzModel.PropertyAdPropertyAdPic", "PropertyAd").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PropertyAd>("TK1ClientBizzModel.PropertyAdPropertyAdPic", "PropertyAd").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PropertyAd> PropertyAdReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PropertyAd>("TK1ClientBizzModel.PropertyAdPropertyAdPic", "PropertyAd");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PropertyAd>("TK1ClientBizzModel.PropertyAdPropertyAdPic", "PropertyAd", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TK1ClientBizzModel", Name="PropertyReleaseAd")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PropertyReleaseAd : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PropertyReleaseAd object.
        /// </summary>
        /// <param name="propertyAdID">Initial value of the PropertyAdID property.</param>
        /// <param name="propertyAdTypeID">Initial value of the PropertyAdTypeID property.</param>
        /// <param name="customerCode">Initial value of the CustomerCode property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="addressComplement">Initial value of the AddressComplement property.</param>
        /// <param name="addressNumber">Initial value of the AddressNumber property.</param>
        /// <param name="minTotalArea">Initial value of the MinTotalArea property.</param>
        /// <param name="maxTotalArea">Initial value of the MaxTotalArea property.</param>
        /// <param name="minTotalRooms">Initial value of the MinTotalRooms property.</param>
        /// <param name="maxTotalRooms">Initial value of the MaxTotalRooms property.</param>
        /// <param name="minSuites">Initial value of the MinSuites property.</param>
        /// <param name="maxSuites">Initial value of the MaxSuites property.</param>
        /// <param name="minInternalArea">Initial value of the MinInternalArea property.</param>
        /// <param name="maxInternalArea">Initial value of the MaxInternalArea property.</param>
        /// <param name="minExternalArea">Initial value of the MinExternalArea property.</param>
        /// <param name="maxExternalArea">Initial value of the MaxExternalArea property.</param>
        /// <param name="minValue">Initial value of the MinValue property.</param>
        /// <param name="maxValue">Initial value of the MaxValue property.</param>
        /// <param name="elevatorNumber">Initial value of the ElevatorNumber property.</param>
        /// <param name="minGarageNumber">Initial value of the MinGarageNumber property.</param>
        /// <param name="maxGarageNumber">Initial value of the MaxGarageNumber property.</param>
        /// <param name="totalFloorUnitNumber">Initial value of the TotalFloorUnitNumber property.</param>
        /// <param name="totalUnitNumber">Initial value of the TotalUnitNumber property.</param>
        /// <param name="towerNumber">Initial value of the TowerNumber property.</param>
        /// <param name="towerFloorNumber">Initial value of the TowerFloorNumber property.</param>
        public static PropertyReleaseAd CreatePropertyReleaseAd(global::System.String propertyAdID, global::System.String propertyAdTypeID, global::System.String customerCode, global::System.String address, global::System.String addressComplement, global::System.Int32 addressNumber, global::System.Single minTotalArea, global::System.Single maxTotalArea, global::System.Int32 minTotalRooms, global::System.Int32 maxTotalRooms, global::System.Int32 minSuites, global::System.Int32 maxSuites, global::System.Single minInternalArea, global::System.Single maxInternalArea, global::System.Single minExternalArea, global::System.Single maxExternalArea, global::System.Single minValue, global::System.Single maxValue, global::System.Int32 elevatorNumber, global::System.Int32 minGarageNumber, global::System.Int32 maxGarageNumber, global::System.Int32 totalFloorUnitNumber, global::System.Int32 totalUnitNumber, global::System.Int32 towerNumber, global::System.Int32 towerFloorNumber)
        {
            PropertyReleaseAd propertyReleaseAd = new PropertyReleaseAd();
            propertyReleaseAd.PropertyAdID = propertyAdID;
            propertyReleaseAd.PropertyAdTypeID = propertyAdTypeID;
            propertyReleaseAd.CustomerCode = customerCode;
            propertyReleaseAd.Address = address;
            propertyReleaseAd.AddressComplement = addressComplement;
            propertyReleaseAd.AddressNumber = addressNumber;
            propertyReleaseAd.MinTotalArea = minTotalArea;
            propertyReleaseAd.MaxTotalArea = maxTotalArea;
            propertyReleaseAd.MinTotalRooms = minTotalRooms;
            propertyReleaseAd.MaxTotalRooms = maxTotalRooms;
            propertyReleaseAd.MinSuites = minSuites;
            propertyReleaseAd.MaxSuites = maxSuites;
            propertyReleaseAd.MinInternalArea = minInternalArea;
            propertyReleaseAd.MaxInternalArea = maxInternalArea;
            propertyReleaseAd.MinExternalArea = minExternalArea;
            propertyReleaseAd.MaxExternalArea = maxExternalArea;
            propertyReleaseAd.MinValue = minValue;
            propertyReleaseAd.MaxValue = maxValue;
            propertyReleaseAd.ElevatorNumber = elevatorNumber;
            propertyReleaseAd.MinGarageNumber = minGarageNumber;
            propertyReleaseAd.MaxGarageNumber = maxGarageNumber;
            propertyReleaseAd.TotalFloorUnitNumber = totalFloorUnitNumber;
            propertyReleaseAd.TotalUnitNumber = totalUnitNumber;
            propertyReleaseAd.TowerNumber = towerNumber;
            propertyReleaseAd.TowerFloorNumber = towerFloorNumber;
            return propertyReleaseAd;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PropertyAdID
        {
            get
            {
                return _PropertyAdID;
            }
            set
            {
                if (_PropertyAdID != value)
                {
                    OnPropertyAdIDChanging(value);
                    ReportPropertyChanging("PropertyAdID");
                    _PropertyAdID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PropertyAdID");
                    OnPropertyAdIDChanged();
                }
            }
        }
        private global::System.String _PropertyAdID;
        partial void OnPropertyAdIDChanging(global::System.String value);
        partial void OnPropertyAdIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PropertyAdTypeID
        {
            get
            {
                return _PropertyAdTypeID;
            }
            set
            {
                if (_PropertyAdTypeID != value)
                {
                    OnPropertyAdTypeIDChanging(value);
                    ReportPropertyChanging("PropertyAdTypeID");
                    _PropertyAdTypeID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PropertyAdTypeID");
                    OnPropertyAdTypeIDChanged();
                }
            }
        }
        private global::System.String _PropertyAdTypeID;
        partial void OnPropertyAdTypeIDChanging(global::System.String value);
        partial void OnPropertyAdTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerCode
        {
            get
            {
                return _CustomerCode;
            }
            set
            {
                if (_CustomerCode != value)
                {
                    OnCustomerCodeChanging(value);
                    ReportPropertyChanging("CustomerCode");
                    _CustomerCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CustomerCode");
                    OnCustomerCodeChanged();
                }
            }
        }
        private global::System.String _CustomerCode;
        partial void OnCustomerCodeChanging(global::System.String value);
        partial void OnCustomerCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ConstructorName
        {
            get
            {
                return _ConstructorName;
            }
            set
            {
                OnConstructorNameChanging(value);
                ReportPropertyChanging("ConstructorName");
                _ConstructorName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ConstructorName");
                OnConstructorNameChanged();
            }
        }
        private global::System.String _ConstructorName;
        partial void OnConstructorNameChanging(global::System.String value);
        partial void OnConstructorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddressComplement
        {
            get
            {
                return _AddressComplement;
            }
            set
            {
                OnAddressComplementChanging(value);
                ReportPropertyChanging("AddressComplement");
                _AddressComplement = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddressComplement");
                OnAddressComplementChanged();
            }
        }
        private global::System.String _AddressComplement;
        partial void OnAddressComplementChanging(global::System.String value);
        partial void OnAddressComplementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddressNumber
        {
            get
            {
                return _AddressNumber;
            }
            set
            {
                OnAddressNumberChanging(value);
                ReportPropertyChanging("AddressNumber");
                _AddressNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddressNumber");
                OnAddressNumberChanged();
            }
        }
        private global::System.Int32 _AddressNumber;
        partial void OnAddressNumberChanging(global::System.Int32 value);
        partial void OnAddressNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MinTotalArea
        {
            get
            {
                return _MinTotalArea;
            }
            set
            {
                OnMinTotalAreaChanging(value);
                ReportPropertyChanging("MinTotalArea");
                _MinTotalArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinTotalArea");
                OnMinTotalAreaChanged();
            }
        }
        private global::System.Single _MinTotalArea;
        partial void OnMinTotalAreaChanging(global::System.Single value);
        partial void OnMinTotalAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MaxTotalArea
        {
            get
            {
                return _MaxTotalArea;
            }
            set
            {
                OnMaxTotalAreaChanging(value);
                ReportPropertyChanging("MaxTotalArea");
                _MaxTotalArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxTotalArea");
                OnMaxTotalAreaChanged();
            }
        }
        private global::System.Single _MaxTotalArea;
        partial void OnMaxTotalAreaChanging(global::System.Single value);
        partial void OnMaxTotalAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MinTotalRooms
        {
            get
            {
                return _MinTotalRooms;
            }
            set
            {
                OnMinTotalRoomsChanging(value);
                ReportPropertyChanging("MinTotalRooms");
                _MinTotalRooms = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinTotalRooms");
                OnMinTotalRoomsChanged();
            }
        }
        private global::System.Int32 _MinTotalRooms;
        partial void OnMinTotalRoomsChanging(global::System.Int32 value);
        partial void OnMinTotalRoomsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaxTotalRooms
        {
            get
            {
                return _MaxTotalRooms;
            }
            set
            {
                OnMaxTotalRoomsChanging(value);
                ReportPropertyChanging("MaxTotalRooms");
                _MaxTotalRooms = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxTotalRooms");
                OnMaxTotalRoomsChanged();
            }
        }
        private global::System.Int32 _MaxTotalRooms;
        partial void OnMaxTotalRoomsChanging(global::System.Int32 value);
        partial void OnMaxTotalRoomsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MinSuites
        {
            get
            {
                return _MinSuites;
            }
            set
            {
                OnMinSuitesChanging(value);
                ReportPropertyChanging("MinSuites");
                _MinSuites = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinSuites");
                OnMinSuitesChanged();
            }
        }
        private global::System.Int32 _MinSuites;
        partial void OnMinSuitesChanging(global::System.Int32 value);
        partial void OnMinSuitesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaxSuites
        {
            get
            {
                return _MaxSuites;
            }
            set
            {
                OnMaxSuitesChanging(value);
                ReportPropertyChanging("MaxSuites");
                _MaxSuites = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxSuites");
                OnMaxSuitesChanged();
            }
        }
        private global::System.Int32 _MaxSuites;
        partial void OnMaxSuitesChanging(global::System.Int32 value);
        partial void OnMaxSuitesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MinInternalArea
        {
            get
            {
                return _MinInternalArea;
            }
            set
            {
                OnMinInternalAreaChanging(value);
                ReportPropertyChanging("MinInternalArea");
                _MinInternalArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinInternalArea");
                OnMinInternalAreaChanged();
            }
        }
        private global::System.Single _MinInternalArea;
        partial void OnMinInternalAreaChanging(global::System.Single value);
        partial void OnMinInternalAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MaxInternalArea
        {
            get
            {
                return _MaxInternalArea;
            }
            set
            {
                OnMaxInternalAreaChanging(value);
                ReportPropertyChanging("MaxInternalArea");
                _MaxInternalArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxInternalArea");
                OnMaxInternalAreaChanged();
            }
        }
        private global::System.Single _MaxInternalArea;
        partial void OnMaxInternalAreaChanging(global::System.Single value);
        partial void OnMaxInternalAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MinExternalArea
        {
            get
            {
                return _MinExternalArea;
            }
            set
            {
                OnMinExternalAreaChanging(value);
                ReportPropertyChanging("MinExternalArea");
                _MinExternalArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinExternalArea");
                OnMinExternalAreaChanged();
            }
        }
        private global::System.Single _MinExternalArea;
        partial void OnMinExternalAreaChanging(global::System.Single value);
        partial void OnMinExternalAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MaxExternalArea
        {
            get
            {
                return _MaxExternalArea;
            }
            set
            {
                OnMaxExternalAreaChanging(value);
                ReportPropertyChanging("MaxExternalArea");
                _MaxExternalArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxExternalArea");
                OnMaxExternalAreaChanged();
            }
        }
        private global::System.Single _MaxExternalArea;
        partial void OnMaxExternalAreaChanging(global::System.Single value);
        partial void OnMaxExternalAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MinValue
        {
            get
            {
                return _MinValue;
            }
            set
            {
                OnMinValueChanging(value);
                ReportPropertyChanging("MinValue");
                _MinValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinValue");
                OnMinValueChanged();
            }
        }
        private global::System.Single _MinValue;
        partial void OnMinValueChanging(global::System.Single value);
        partial void OnMinValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single MaxValue
        {
            get
            {
                return _MaxValue;
            }
            set
            {
                OnMaxValueChanging(value);
                ReportPropertyChanging("MaxValue");
                _MaxValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxValue");
                OnMaxValueChanged();
            }
        }
        private global::System.Single _MaxValue;
        partial void OnMaxValueChanging(global::System.Single value);
        partial void OnMaxValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ElevatorNumber
        {
            get
            {
                return _ElevatorNumber;
            }
            set
            {
                OnElevatorNumberChanging(value);
                ReportPropertyChanging("ElevatorNumber");
                _ElevatorNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ElevatorNumber");
                OnElevatorNumberChanged();
            }
        }
        private global::System.Int32 _ElevatorNumber;
        partial void OnElevatorNumberChanging(global::System.Int32 value);
        partial void OnElevatorNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MinGarageNumber
        {
            get
            {
                return _MinGarageNumber;
            }
            set
            {
                OnMinGarageNumberChanging(value);
                ReportPropertyChanging("MinGarageNumber");
                _MinGarageNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinGarageNumber");
                OnMinGarageNumberChanged();
            }
        }
        private global::System.Int32 _MinGarageNumber;
        partial void OnMinGarageNumberChanging(global::System.Int32 value);
        partial void OnMinGarageNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaxGarageNumber
        {
            get
            {
                return _MaxGarageNumber;
            }
            set
            {
                OnMaxGarageNumberChanging(value);
                ReportPropertyChanging("MaxGarageNumber");
                _MaxGarageNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxGarageNumber");
                OnMaxGarageNumberChanged();
            }
        }
        private global::System.Int32 _MaxGarageNumber;
        partial void OnMaxGarageNumberChanging(global::System.Int32 value);
        partial void OnMaxGarageNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalFloorUnitNumber
        {
            get
            {
                return _TotalFloorUnitNumber;
            }
            set
            {
                OnTotalFloorUnitNumberChanging(value);
                ReportPropertyChanging("TotalFloorUnitNumber");
                _TotalFloorUnitNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalFloorUnitNumber");
                OnTotalFloorUnitNumberChanged();
            }
        }
        private global::System.Int32 _TotalFloorUnitNumber;
        partial void OnTotalFloorUnitNumberChanging(global::System.Int32 value);
        partial void OnTotalFloorUnitNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalUnitNumber
        {
            get
            {
                return _TotalUnitNumber;
            }
            set
            {
                OnTotalUnitNumberChanging(value);
                ReportPropertyChanging("TotalUnitNumber");
                _TotalUnitNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalUnitNumber");
                OnTotalUnitNumberChanged();
            }
        }
        private global::System.Int32 _TotalUnitNumber;
        partial void OnTotalUnitNumberChanging(global::System.Int32 value);
        partial void OnTotalUnitNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TowerNumber
        {
            get
            {
                return _TowerNumber;
            }
            set
            {
                OnTowerNumberChanging(value);
                ReportPropertyChanging("TowerNumber");
                _TowerNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TowerNumber");
                OnTowerNumberChanged();
            }
        }
        private global::System.Int32 _TowerNumber;
        partial void OnTowerNumberChanging(global::System.Int32 value);
        partial void OnTowerNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TowerFloorNumber
        {
            get
            {
                return _TowerFloorNumber;
            }
            set
            {
                OnTowerFloorNumberChanging(value);
                ReportPropertyChanging("TowerFloorNumber");
                _TowerFloorNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TowerFloorNumber");
                OnTowerFloorNumberChanged();
            }
        }
        private global::System.Int32 _TowerFloorNumber;
        partial void OnTowerFloorNumberChanging(global::System.Int32 value);
        partial void OnTowerFloorNumberChanged();

        #endregion

    
    }

    #endregion

    
}
