///////////////////////////////////////////////////////////
//  EventLogEntryType.cs
//  Implementation of the Class EventLogEntryType
//  Generated by Enterprise Architect
//  Created on:      06-out-2008 16:19:34
//  Original author: andre
///////////////////////////////////////////////////////////




namespace TK1.Diagnostics {
	/// <summary>
	/// Tipos de entradas de eventLog (Info, Warning, Error)
	/// </summary>
	public enum EventLogEntryType : int {

        /// <summary>
        /// Informação
        /// </summary>
        Info = System.Diagnostics.EventLogEntryType.Information,
        /// <summary>
        /// Atenção
        /// </summary>
        Warning = System.Diagnostics.EventLogEntryType.Warning,
        /// <summary>
        /// Erro
        /// </summary>
        Error = System.Diagnostics.EventLogEntryType.Error

	}//end EventLogEntryType

}//end namespace Diagnostics