//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK1.Data.Bizz.Broker.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BrokerEntities : DbContext
    {
        public BrokerEntities()
            : base("name=BrokerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PropertyAd> PropertyAds { get; set; }
        public DbSet<PropertyAdCodeGenerator> PropertyAdCodeGenerators { get; set; }
        public DbSet<PropertyAdDetail> PropertyAdDetails { get; set; }
        public DbSet<PropertyAdPic> PropertyAdPics { get; set; }
        public DbSet<PropertyReleaseAd> PropertyReleaseAds { get; set; }
    }
}
