//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK1.Data.Bizz.Broker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyAdDetail
    {
        public int PropertyAdDetailID { get; set; }
        public string CustomerCode { get; set; }
        public string PropertyAdType { get; set; }
        public int PropertyAdCode { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public string Type { get; set; }
    
        public virtual PropertyAd PropertyAd { get; set; }
    }
}
