//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK1.Data.Bizz.Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAudit
    {
        public int AuditID { get; set; }
        public string GUID { get; set; }
        public System.DateTime EventTimestamp { get; set; }
        public int EventType { get; set; }
        public string Assembly { get; set; }
        public string Source { get; set; }
        public string Message { get; set; }
        public string Data { get; set; }
        public string CustomerCode { get; set; }
        public string ProcessName { get; set; }
        public bool ReportVisible { get; set; }
    }
}
