//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK1.Data.Bizz.Client.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TK1ClientBaseEntities : DbContext
    {
        public TK1ClientBaseEntities()
            : base("name=TK1ClientBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClientAppLog> ClientAppLog { get; set; }
        public DbSet<ClientConfiguration> ClientConfiguration { get; set; }
        public DbSet<ClientAudit> ClientAudit { get; set; }
    }
}
