//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK1.Data.Bizz.Client.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TK1ClientBizzEntities : DbContext
    {
        public TK1ClientBizzEntities()
            : base("name=TK1ClientBizzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PropertyAd> PropertyAd { get; set; }
        public DbSet<PropertyAdDetail> PropertyAdDetail { get; set; }
        public DbSet<PropertyAdPic> PropertyAdPic { get; set; }
        public DbSet<PropertyReleaseAd> PropertyReleaseAd { get; set; }
    }
}
