//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK1.Data.Bizz.Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyReleaseAd
    {
        public int PropertyAdID { get; set; }
        public string PropertyAdTypeID { get; set; }
        public string CustomerCode { get; set; }
        public string Name { get; set; }
        public string ConstructorName { get; set; }
        public string Address { get; set; }
        public string AddressComplement { get; set; }
        public int AddressNumber { get; set; }
        public float MinTotalArea { get; set; }
        public float MaxTotalArea { get; set; }
        public int MinTotalRooms { get; set; }
        public int MaxTotalRooms { get; set; }
        public int MinSuites { get; set; }
        public int MaxSuites { get; set; }
        public float MinInternalArea { get; set; }
        public float MaxInternalArea { get; set; }
        public float MinExternalArea { get; set; }
        public float MaxExternalArea { get; set; }
        public float MinValue { get; set; }
        public float MaxValue { get; set; }
        public int TotalElevators { get; set; }
        public int TotalFloorUnits { get; set; }
        public int TotalUnits { get; set; }
        public int TotalTowers { get; set; }
        public int TotalTowerFloors { get; set; }
        public int MinParkingLots { get; set; }
        public int MaxParkingLots { get; set; }
    
        public virtual PropertyAd PropertyAd { get; set; }
    }
}
