//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK1.Data.Bizz.Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyAdPic
    {
        public int PropertyAdPicID { get; set; }
        public int PropertyAdID { get; set; }
        public string PropertyAdTypeID { get; set; }
        public string CustomerCode { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string PictureUrl { get; set; }
        public string ThumbnailUrl { get; set; }
        public string PictureFilePath { get; set; }
        public string ThumbnailFilePath { get; set; }
    
        public virtual PropertyAd PropertyAd { get; set; }
    }
}
