///////////////////////////////////////////////////////////
//  ErrorManagerEventArgs.cs
//  Implementation of the Class ErrorManagerEventArgs
//  Generated by Enterprise Architect
//  Created on:      06-out-2008 17:10:16
//  Original author: andre
///////////////////////////////////////////////////////////



using System;
namespace Took1.Silverlight.Diagnostics
{
    public class ErrorManagerEventArgs : EventArgs
    {
        public string Message { get; set; }
        public string Source { get; set; }
        public EventLogEntryType EntryType { get; set; }
	}//end ErrorManagerEventArgs

}//end namespace Diagnostics