///////////////////////////////////////////////////////////
//  EventLogEntryType.cs
//  Implementation of the Class EventLogEntryType
//  Generated by Enterprise Architect
//  Created on:      06-out-2008 16:19:34
//  Original author: andre
///////////////////////////////////////////////////////////




namespace Took1.Silverlight.Diagnostics
{
	/// <summary>
	/// Tipos de entradas de eventLog (Info, Warning, Error)
	/// </summary>
	public enum EventLogEntryType : int {

		Info = 0,
        Warning = 1,
        Error = 2

	}//end EventLogEntryType

}//end namespace Diagnostics