//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TK1.Resources.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {EMPTY}.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR].
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR IN {1}]{0}{2}:{0}{3}.
        /// </summary>
        public static string ErrorMessageKnownAction {
            get {
                return ResourceManager.GetString("ErrorMessageKnownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR IN UNKNOWN ACTION]{0}{1}:{0}{2}.
        /// </summary>
        public static string ErrorMessageUnknownAction {
            get {
                return ResourceManager.GetString("ErrorMessageUnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EXCEPTION].
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EXCEPTION IN {1}]{0}{2}:{0}{3}.
        /// </summary>
        public static string ExceptionMessageKnownAction {
            get {
                return ResourceManager.GetString("ExceptionMessageKnownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EXCEPTION IN UNKNOWN ACTION]{0}{1}:{0}{2}.
        /// </summary>
        public static string ExceptionMessageUnknownAction {
            get {
                return ResourceManager.GetString("ExceptionMessageUnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INNER EXCEPTION].
        /// </summary>
        public static string InnerException {
            get {
                return ResourceManager.GetString("InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}:{0}{2}.
        /// </summary>
        public static string InnerExceptionMessage {
            get {
                return ResourceManager.GetString("InnerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {NULL}.
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {NULL EXCEPTION}.
        /// </summary>
        public static string NullException {
            get {
                return ResourceManager.GetString("NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {NULL MESSAGE}.
        /// </summary>
        public static string NullMessage {
            get {
                return ResourceManager.GetString("NullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {NULL OR EMPTY}.
        /// </summary>
        public static string NullOrEmpty {
            get {
                return ResourceManager.GetString("NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}[STACK TRACE]:{0}{1}.
        /// </summary>
        public static string StackTraceMessage {
            get {
                return ResourceManager.GetString("StackTraceMessage", resourceCulture);
            }
        }
    }
}
