//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK1.Data.Bizz.Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientConfiguration
    {
        public int ConfigurationID { get; set; }
        public string CustomerCode { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public string Group { get; set; }
        public string Type { get; set; }
    }
}
