//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TK1.Bizz.Client.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TK1ClientBaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TK1ClientBaseEntities object using the connection string found in the 'TK1ClientBaseEntities' section of the application configuration file.
        /// </summary>
        public TK1ClientBaseEntities() : base("name=TK1ClientBaseEntities", "TK1ClientBaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TK1ClientBaseEntities object.
        /// </summary>
        public TK1ClientBaseEntities(string connectionString) : base(connectionString, "TK1ClientBaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TK1ClientBaseEntities object.
        /// </summary>
        public TK1ClientBaseEntities(EntityConnection connection) : base(connection, "TK1ClientBaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClientAppLog> ClientAppLog
        {
            get
            {
                if ((_ClientAppLog == null))
                {
                    _ClientAppLog = base.CreateObjectSet<ClientAppLog>("ClientAppLog");
                }
                return _ClientAppLog;
            }
        }
        private ObjectSet<ClientAppLog> _ClientAppLog;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClientAppLog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientAppLog(ClientAppLog clientAppLog)
        {
            base.AddObject("ClientAppLog", clientAppLog);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TK1ClientBaseModel", Name="ClientAppLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClientAppLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClientAppLog object.
        /// </summary>
        /// <param name="appLogID">Initial value of the AppLogID property.</param>
        /// <param name="logTimestamp">Initial value of the LogTimestamp property.</param>
        /// <param name="logType">Initial value of the LogType property.</param>
        public static ClientAppLog CreateClientAppLog(global::System.Int32 appLogID, global::System.DateTime logTimestamp, global::System.Int32 logType)
        {
            ClientAppLog clientAppLog = new ClientAppLog();
            clientAppLog.AppLogID = appLogID;
            clientAppLog.LogTimestamp = logTimestamp;
            clientAppLog.LogType = logType;
            return clientAppLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppLogID
        {
            get
            {
                return _AppLogID;
            }
            set
            {
                if (_AppLogID != value)
                {
                    OnAppLogIDChanging(value);
                    ReportPropertyChanging("AppLogID");
                    _AppLogID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppLogID");
                    OnAppLogIDChanged();
                }
            }
        }
        private global::System.Int32 _AppLogID;
        partial void OnAppLogIDChanging(global::System.Int32 value);
        partial void OnAppLogIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LogTimestamp
        {
            get
            {
                return _LogTimestamp;
            }
            set
            {
                OnLogTimestampChanging(value);
                ReportPropertyChanging("LogTimestamp");
                _LogTimestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LogTimestamp");
                OnLogTimestampChanged();
            }
        }
        private global::System.DateTime _LogTimestamp;
        partial void OnLogTimestampChanging(global::System.DateTime value);
        partial void OnLogTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LogType
        {
            get
            {
                return _LogType;
            }
            set
            {
                OnLogTypeChanging(value);
                ReportPropertyChanging("LogType");
                _LogType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LogType");
                OnLogTypeChanged();
            }
        }
        private global::System.Int32 _LogType;
        partial void OnLogTypeChanging(global::System.Int32 value);
        partial void OnLogTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.String _Data;
        partial void OnDataChanging(global::System.String value);
        partial void OnDataChanged();

        #endregion

    
    }

    #endregion

    
}
