//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TK1Model", "FK_SiteAd_SiteAdType", "SiteAdType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TK1.Bizz.Data.SiteAdType), "SiteAd", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TK1.Bizz.Data.SiteAd), true)]
[assembly: EdmRelationshipAttribute("TK1Model", "FK_SiteAdDetail_SiteAd", "SiteAd", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TK1.Bizz.Data.SiteAd), "SiteAdDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TK1.Bizz.Data.SiteAdDetail), true)]
[assembly: EdmRelationshipAttribute("TK1Model", "FK_SiteAdPic_SiteAd", "SiteAd", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TK1.Bizz.Data.SiteAd), "SiteAdPic", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TK1.Bizz.Data.SiteAdPic), true)]

#endregion

namespace TK1.Bizz.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BizzEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BizzEntities object using the connection string found in the 'BizzEntities' section of the application configuration file.
        /// </summary>
        public BizzEntities() : base("name=BizzEntities", "BizzEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BizzEntities object.
        /// </summary>
        public BizzEntities(string connectionString) : base(connectionString, "BizzEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BizzEntities object.
        /// </summary>
        public BizzEntities(EntityConnection connection) : base(connection, "BizzEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SiteAdType> SiteAdTypes
        {
            get
            {
                if ((_SiteAdTypes == null))
                {
                    _SiteAdTypes = base.CreateObjectSet<SiteAdType>("SiteAdTypes");
                }
                return _SiteAdTypes;
            }
        }
        private ObjectSet<SiteAdType> _SiteAdTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SiteAd> SiteAds
        {
            get
            {
                if ((_SiteAds == null))
                {
                    _SiteAds = base.CreateObjectSet<SiteAd>("SiteAds");
                }
                return _SiteAds;
            }
        }
        private ObjectSet<SiteAd> _SiteAds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SiteAdDetail> SiteAdDetails
        {
            get
            {
                if ((_SiteAdDetails == null))
                {
                    _SiteAdDetails = base.CreateObjectSet<SiteAdDetail>("SiteAdDetails");
                }
                return _SiteAdDetails;
            }
        }
        private ObjectSet<SiteAdDetail> _SiteAdDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SiteAdPic> SiteAdPics
        {
            get
            {
                if ((_SiteAdPics == null))
                {
                    _SiteAdPics = base.CreateObjectSet<SiteAdPic>("SiteAdPics");
                }
                return _SiteAdPics;
            }
        }
        private ObjectSet<SiteAdPic> _SiteAdPics;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SiteAdTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSiteAdTypes(SiteAdType siteAdType)
        {
            base.AddObject("SiteAdTypes", siteAdType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SiteAds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSiteAds(SiteAd siteAd)
        {
            base.AddObject("SiteAds", siteAd);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SiteAdDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSiteAdDetails(SiteAdDetail siteAdDetail)
        {
            base.AddObject("SiteAdDetails", siteAdDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SiteAdPics EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSiteAdPics(SiteAdPic siteAdPic)
        {
            base.AddObject("SiteAdPics", siteAdPic);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TK1Model", Name="SiteAd")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SiteAd : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SiteAd object.
        /// </summary>
        /// <param name="siteAdID">Initial value of the SiteAdID property.</param>
        /// <param name="siteAdTypeID">Initial value of the SiteAdTypeID property.</param>
        /// <param name="customerCodename">Initial value of the CustomerCodename property.</param>
        /// <param name="categoryName">Initial value of the CategoryName property.</param>
        /// <param name="cityName">Initial value of the CityName property.</param>
        /// <param name="districtName">Initial value of the DistrictName property.</param>
        /// <param name="totalArea">Initial value of the TotalArea property.</param>
        /// <param name="totalRooms">Initial value of the TotalRooms property.</param>
        /// <param name="internalArea">Initial value of the InternalArea property.</param>
        /// <param name="externalArea">Initial value of the ExternalArea property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static SiteAd CreateSiteAd(global::System.Int32 siteAdID, global::System.Int32 siteAdTypeID, global::System.String customerCodename, global::System.String categoryName, global::System.String cityName, global::System.String districtName, global::System.Double totalArea, global::System.Int32 totalRooms, global::System.Double internalArea, global::System.Double externalArea, global::System.Double value)
        {
            SiteAd siteAd = new SiteAd();
            siteAd.SiteAdID = siteAdID;
            siteAd.SiteAdTypeID = siteAdTypeID;
            siteAd.CustomerCodename = customerCodename;
            siteAd.CategoryName = categoryName;
            siteAd.CityName = cityName;
            siteAd.DistrictName = districtName;
            siteAd.TotalArea = totalArea;
            siteAd.TotalRooms = totalRooms;
            siteAd.InternalArea = internalArea;
            siteAd.ExternalArea = externalArea;
            siteAd.Value = value;
            return siteAd;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteAdID
        {
            get
            {
                return _SiteAdID;
            }
            set
            {
                if (_SiteAdID != value)
                {
                    OnSiteAdIDChanging(value);
                    ReportPropertyChanging("SiteAdID");
                    _SiteAdID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SiteAdID");
                    OnSiteAdIDChanged();
                }
            }
        }
        private global::System.Int32 _SiteAdID;
        partial void OnSiteAdIDChanging(global::System.Int32 value);
        partial void OnSiteAdIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteAdTypeID
        {
            get
            {
                return _SiteAdTypeID;
            }
            set
            {
                if (_SiteAdTypeID != value)
                {
                    OnSiteAdTypeIDChanging(value);
                    ReportPropertyChanging("SiteAdTypeID");
                    _SiteAdTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SiteAdTypeID");
                    OnSiteAdTypeIDChanged();
                }
            }
        }
        private global::System.Int32 _SiteAdTypeID;
        partial void OnSiteAdTypeIDChanging(global::System.Int32 value);
        partial void OnSiteAdTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerCodename
        {
            get
            {
                return _CustomerCodename;
            }
            set
            {
                if (_CustomerCodename != value)
                {
                    OnCustomerCodenameChanging(value);
                    ReportPropertyChanging("CustomerCodename");
                    _CustomerCodename = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CustomerCodename");
                    OnCustomerCodenameChanged();
                }
            }
        }
        private global::System.String _CustomerCodename;
        partial void OnCustomerCodenameChanging(global::System.String value);
        partial void OnCustomerCodenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SiteTypeName
        {
            get
            {
                return _SiteTypeName;
            }
            set
            {
                OnSiteTypeNameChanging(value);
                ReportPropertyChanging("SiteTypeName");
                _SiteTypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SiteTypeName");
                OnSiteTypeNameChanged();
            }
        }
        private global::System.String _SiteTypeName;
        partial void OnSiteTypeNameChanging(global::System.String value);
        partial void OnSiteTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CityName
        {
            get
            {
                return _CityName;
            }
            set
            {
                OnCityNameChanging(value);
                ReportPropertyChanging("CityName");
                _CityName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CityName");
                OnCityNameChanged();
            }
        }
        private global::System.String _CityName;
        partial void OnCityNameChanging(global::System.String value);
        partial void OnCityNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DistrictName
        {
            get
            {
                return _DistrictName;
            }
            set
            {
                OnDistrictNameChanging(value);
                ReportPropertyChanging("DistrictName");
                _DistrictName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DistrictName");
                OnDistrictNameChanged();
            }
        }
        private global::System.String _DistrictName;
        partial void OnDistrictNameChanging(global::System.String value);
        partial void OnDistrictNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double TotalArea
        {
            get
            {
                return _TotalArea;
            }
            set
            {
                OnTotalAreaChanging(value);
                ReportPropertyChanging("TotalArea");
                _TotalArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalArea");
                OnTotalAreaChanged();
            }
        }
        private global::System.Double _TotalArea;
        partial void OnTotalAreaChanging(global::System.Double value);
        partial void OnTotalAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalRooms
        {
            get
            {
                return _TotalRooms;
            }
            set
            {
                OnTotalRoomsChanging(value);
                ReportPropertyChanging("TotalRooms");
                _TotalRooms = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalRooms");
                OnTotalRoomsChanged();
            }
        }
        private global::System.Int32 _TotalRooms;
        partial void OnTotalRoomsChanging(global::System.Int32 value);
        partial void OnTotalRoomsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double InternalArea
        {
            get
            {
                return _InternalArea;
            }
            set
            {
                OnInternalAreaChanging(value);
                ReportPropertyChanging("InternalArea");
                _InternalArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InternalArea");
                OnInternalAreaChanged();
            }
        }
        private global::System.Double _InternalArea;
        partial void OnInternalAreaChanging(global::System.Double value);
        partial void OnInternalAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ExternalArea
        {
            get
            {
                return _ExternalArea;
            }
            set
            {
                OnExternalAreaChanging(value);
                ReportPropertyChanging("ExternalArea");
                _ExternalArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExternalArea");
                OnExternalAreaChanged();
            }
        }
        private global::System.Double _ExternalArea;
        partial void OnExternalAreaChanging(global::System.Double value);
        partial void OnExternalAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Double _Value;
        partial void OnValueChanging(global::System.Double value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CityTaxes
        {
            get
            {
                return _CityTaxes;
            }
            set
            {
                OnCityTaxesChanging(value);
                ReportPropertyChanging("CityTaxes");
                _CityTaxes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CityTaxes");
                OnCityTaxesChanged();
            }
        }
        private Nullable<global::System.Double> _CityTaxes;
        partial void OnCityTaxesChanging(Nullable<global::System.Double> value);
        partial void OnCityTaxesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CondoTaxes
        {
            get
            {
                return _CondoTaxes;
            }
            set
            {
                OnCondoTaxesChanging(value);
                ReportPropertyChanging("CondoTaxes");
                _CondoTaxes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CondoTaxes");
                OnCondoTaxesChanged();
            }
        }
        private Nullable<global::System.Double> _CondoTaxes;
        partial void OnCondoTaxesChanging(Nullable<global::System.Double> value);
        partial void OnCondoTaxesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShortDescription
        {
            get
            {
                return _ShortDescription;
            }
            set
            {
                OnShortDescriptionChanging(value);
                ReportPropertyChanging("ShortDescription");
                _ShortDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShortDescription");
                OnShortDescriptionChanged();
            }
        }
        private global::System.String _ShortDescription;
        partial void OnShortDescriptionChanging(global::System.String value);
        partial void OnShortDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullDescription
        {
            get
            {
                return _FullDescription;
            }
            set
            {
                OnFullDescriptionChanging(value);
                ReportPropertyChanging("FullDescription");
                _FullDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullDescription");
                OnFullDescriptionChanged();
            }
        }
        private global::System.String _FullDescription;
        partial void OnFullDescriptionChanging(global::System.String value);
        partial void OnFullDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AreaDescription
        {
            get
            {
                return _AreaDescription;
            }
            set
            {
                OnAreaDescriptionChanging(value);
                ReportPropertyChanging("AreaDescription");
                _AreaDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AreaDescription");
                OnAreaDescriptionChanged();
            }
        }
        private global::System.String _AreaDescription;
        partial void OnAreaDescriptionChanging(global::System.String value);
        partial void OnAreaDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CondoDescription
        {
            get
            {
                return _CondoDescription;
            }
            set
            {
                OnCondoDescriptionChanging(value);
                ReportPropertyChanging("CondoDescription");
                _CondoDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CondoDescription");
                OnCondoDescriptionChanged();
            }
        }
        private global::System.String _CondoDescription;
        partial void OnCondoDescriptionChanging(global::System.String value);
        partial void OnCondoDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TK1Model", "FK_SiteAd_SiteAdType", "SiteAdType")]
        public SiteAdType SiteAdType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SiteAdType>("TK1Model.FK_SiteAd_SiteAdType", "SiteAdType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SiteAdType>("TK1Model.FK_SiteAd_SiteAdType", "SiteAdType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SiteAdType> SiteAdTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SiteAdType>("TK1Model.FK_SiteAd_SiteAdType", "SiteAdType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SiteAdType>("TK1Model.FK_SiteAd_SiteAdType", "SiteAdType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TK1Model", "FK_SiteAdDetail_SiteAd", "SiteAdDetail")]
        public EntityCollection<SiteAdDetail> SiteAdDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SiteAdDetail>("TK1Model.FK_SiteAdDetail_SiteAd", "SiteAdDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SiteAdDetail>("TK1Model.FK_SiteAdDetail_SiteAd", "SiteAdDetail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TK1Model", "FK_SiteAdPic_SiteAd", "SiteAdPic")]
        public EntityCollection<SiteAdPic> SiteAdPics
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SiteAdPic>("TK1Model.FK_SiteAdPic_SiteAd", "SiteAdPic");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SiteAdPic>("TK1Model.FK_SiteAdPic_SiteAd", "SiteAdPic", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TK1Model", Name="SiteAdDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SiteAdDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SiteAdDetail object.
        /// </summary>
        /// <param name="siteAdDetailID">Initial value of the SiteAdDetailID property.</param>
        /// <param name="siteAdID">Initial value of the SiteAdID property.</param>
        /// <param name="siteAdTypeID">Initial value of the SiteAdTypeID property.</param>
        /// <param name="customerCodename">Initial value of the CustomerCodename property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static SiteAdDetail CreateSiteAdDetail(global::System.Int32 siteAdDetailID, global::System.Int32 siteAdID, global::System.Int32 siteAdTypeID, global::System.String customerCodename, global::System.String description, global::System.String value)
        {
            SiteAdDetail siteAdDetail = new SiteAdDetail();
            siteAdDetail.SiteAdDetailID = siteAdDetailID;
            siteAdDetail.SiteAdID = siteAdID;
            siteAdDetail.SiteAdTypeID = siteAdTypeID;
            siteAdDetail.CustomerCodename = customerCodename;
            siteAdDetail.Description = description;
            siteAdDetail.Value = value;
            return siteAdDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteAdDetailID
        {
            get
            {
                return _SiteAdDetailID;
            }
            set
            {
                if (_SiteAdDetailID != value)
                {
                    OnSiteAdDetailIDChanging(value);
                    ReportPropertyChanging("SiteAdDetailID");
                    _SiteAdDetailID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SiteAdDetailID");
                    OnSiteAdDetailIDChanged();
                }
            }
        }
        private global::System.Int32 _SiteAdDetailID;
        partial void OnSiteAdDetailIDChanging(global::System.Int32 value);
        partial void OnSiteAdDetailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteAdID
        {
            get
            {
                return _SiteAdID;
            }
            set
            {
                OnSiteAdIDChanging(value);
                ReportPropertyChanging("SiteAdID");
                _SiteAdID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SiteAdID");
                OnSiteAdIDChanged();
            }
        }
        private global::System.Int32 _SiteAdID;
        partial void OnSiteAdIDChanging(global::System.Int32 value);
        partial void OnSiteAdIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteAdTypeID
        {
            get
            {
                return _SiteAdTypeID;
            }
            set
            {
                OnSiteAdTypeIDChanging(value);
                ReportPropertyChanging("SiteAdTypeID");
                _SiteAdTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SiteAdTypeID");
                OnSiteAdTypeIDChanged();
            }
        }
        private global::System.Int32 _SiteAdTypeID;
        partial void OnSiteAdTypeIDChanging(global::System.Int32 value);
        partial void OnSiteAdTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerCodename
        {
            get
            {
                return _CustomerCodename;
            }
            set
            {
                OnCustomerCodenameChanging(value);
                ReportPropertyChanging("CustomerCodename");
                _CustomerCodename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerCodename");
                OnCustomerCodenameChanged();
            }
        }
        private global::System.String _CustomerCodename;
        partial void OnCustomerCodenameChanging(global::System.String value);
        partial void OnCustomerCodenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TK1Model", "FK_SiteAdDetail_SiteAd", "SiteAd")]
        public SiteAd SiteAd
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SiteAd>("TK1Model.FK_SiteAdDetail_SiteAd", "SiteAd").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SiteAd>("TK1Model.FK_SiteAdDetail_SiteAd", "SiteAd").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SiteAd> SiteAdReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SiteAd>("TK1Model.FK_SiteAdDetail_SiteAd", "SiteAd");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SiteAd>("TK1Model.FK_SiteAdDetail_SiteAd", "SiteAd", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TK1Model", Name="SiteAdPic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SiteAdPic : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SiteAdPic object.
        /// </summary>
        /// <param name="siteAdID">Initial value of the SiteAdID property.</param>
        /// <param name="siteAdTypeID">Initial value of the SiteAdTypeID property.</param>
        /// <param name="customerCodename">Initial value of the CustomerCodename property.</param>
        /// <param name="picID">Initial value of the PicID property.</param>
        public static SiteAdPic CreateSiteAdPic(global::System.Int32 siteAdID, global::System.Int32 siteAdTypeID, global::System.String customerCodename, global::System.Int32 picID)
        {
            SiteAdPic siteAdPic = new SiteAdPic();
            siteAdPic.SiteAdID = siteAdID;
            siteAdPic.SiteAdTypeID = siteAdTypeID;
            siteAdPic.CustomerCodename = customerCodename;
            siteAdPic.PicID = picID;
            return siteAdPic;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteAdID
        {
            get
            {
                return _SiteAdID;
            }
            set
            {
                if (_SiteAdID != value)
                {
                    OnSiteAdIDChanging(value);
                    ReportPropertyChanging("SiteAdID");
                    _SiteAdID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SiteAdID");
                    OnSiteAdIDChanged();
                }
            }
        }
        private global::System.Int32 _SiteAdID;
        partial void OnSiteAdIDChanging(global::System.Int32 value);
        partial void OnSiteAdIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteAdTypeID
        {
            get
            {
                return _SiteAdTypeID;
            }
            set
            {
                if (_SiteAdTypeID != value)
                {
                    OnSiteAdTypeIDChanging(value);
                    ReportPropertyChanging("SiteAdTypeID");
                    _SiteAdTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SiteAdTypeID");
                    OnSiteAdTypeIDChanged();
                }
            }
        }
        private global::System.Int32 _SiteAdTypeID;
        partial void OnSiteAdTypeIDChanging(global::System.Int32 value);
        partial void OnSiteAdTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerCodename
        {
            get
            {
                return _CustomerCodename;
            }
            set
            {
                if (_CustomerCodename != value)
                {
                    OnCustomerCodenameChanging(value);
                    ReportPropertyChanging("CustomerCodename");
                    _CustomerCodename = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CustomerCodename");
                    OnCustomerCodenameChanged();
                }
            }
        }
        private global::System.String _CustomerCodename;
        partial void OnCustomerCodenameChanging(global::System.String value);
        partial void OnCustomerCodenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PicID
        {
            get
            {
                return _PicID;
            }
            set
            {
                if (_PicID != value)
                {
                    OnPicIDChanging(value);
                    ReportPropertyChanging("PicID");
                    _PicID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PicID");
                    OnPicIDChanged();
                }
            }
        }
        private global::System.Int32 _PicID;
        partial void OnPicIDChanging(global::System.Int32 value);
        partial void OnPicIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TK1Model", "FK_SiteAdPic_SiteAd", "SiteAd")]
        public SiteAd SiteAd
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SiteAd>("TK1Model.FK_SiteAdPic_SiteAd", "SiteAd").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SiteAd>("TK1Model.FK_SiteAdPic_SiteAd", "SiteAd").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SiteAd> SiteAdReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SiteAd>("TK1Model.FK_SiteAdPic_SiteAd", "SiteAd");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SiteAd>("TK1Model.FK_SiteAdPic_SiteAd", "SiteAd", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TK1Model", Name="SiteAdType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SiteAdType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SiteAdType object.
        /// </summary>
        /// <param name="siteAdTypeID">Initial value of the SiteAdTypeID property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static SiteAdType CreateSiteAdType(global::System.Int32 siteAdTypeID, global::System.String description)
        {
            SiteAdType siteAdType = new SiteAdType();
            siteAdType.SiteAdTypeID = siteAdTypeID;
            siteAdType.Description = description;
            return siteAdType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteAdTypeID
        {
            get
            {
                return _SiteAdTypeID;
            }
            set
            {
                if (_SiteAdTypeID != value)
                {
                    OnSiteAdTypeIDChanging(value);
                    ReportPropertyChanging("SiteAdTypeID");
                    _SiteAdTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SiteAdTypeID");
                    OnSiteAdTypeIDChanged();
                }
            }
        }
        private global::System.Int32 _SiteAdTypeID;
        partial void OnSiteAdTypeIDChanging(global::System.Int32 value);
        partial void OnSiteAdTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TK1Model", "FK_SiteAd_SiteAdType", "SiteAd")]
        public EntityCollection<SiteAd> SiteAds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SiteAd>("TK1Model.FK_SiteAd_SiteAdType", "SiteAd");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SiteAd>("TK1Model.FK_SiteAd_SiteAdType", "SiteAd", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
